tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "alpine"
brew "ghi"
brew "ghostscript", link: false
brew "htop"
brew "hub"
brew "pandoc"
brew "python"
brew "python@2"
brew "tmux"
cask "fastlane"
